# Site settings
title: SNES Tracker
email: mbazzinottti@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Website for all things SNES Tracker. That is, a tracker interface for the
  Super Nintendo. Should be pretty sweet I hope.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://snestracker.club" # the base hostname & protocol for your site
twitter_username: imyourbazz
github_username:  bazzinotti

# Build settings
markdown: kramdown
excerpt_separator: <!--more-->